language: node_js
node_js:
  - "8.10"
before_install:
  - npm i -g npm@latest
install:
  - npm i
script:
  - mkdir $TRAVIS_BUILD_DIR/../.aws
  - printf "[default]\naws_access_key_id=foo\naws_secret_access_key=bar\nregion=us-west-1\n" > $TRAVIS_BUILD_DIR/../.aws/credentials
  - npm run lint
  - npm run test

