language: node_js
node_js:
  - "8.10"
before_install:
  - npm i -g npm@latest
  - npm --version
install:
  - npm i
script:
  - npm run lint
  - AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar REGION=us-west-1 npm run test
